### ISSUE TITLE
TransferState API doesn't works on fastify 

### ISSUE THREAD

**Issue by manzonif** [exequiel09/fastify-angular-universal#1]
I trying to make works [TransferState](https://blog.angularindepth.com/using-transferstate-api-in-an-angular-5-universal-app-130f3ada9e5b), (for avoid flickering) with fastify and fastify-angular-universal, but [serializeTransferStateFactory ](https://github.com/angular/angular/blob/6e1896b3338563374df40e15445f6feee0ea66d6/packages/platform-server/src/transfer_state.ts) it is never called during the process.

With express all works correctly.

Are you already aware of it?

I'm preparing a test app based on yours, if you are interested.

**Comment by exequiel09** [comment]
Not yet used the TransferState. Can you provide a test application for this? Maybe we can look into integrating it.

Thanks for reporting.

**Comment by exequiel09** [comment]
Following this tutorial: https://medium.com/@evertonrobertoauler/angular-5-universal-with-transfer-state-using-angular-cli-19fe1e1d352c

I created a branch for a [sample integration of TransferState API](https://github.com/exequiel09/fastify-angular-universal/tree/transfer-state-test).

The sample integration is applied on the test application using `@angular/cli` and `fastify`

Let me know what's the issue since a serialized state is already present on my end when rendering an Angular app server-side.

**Comment by manzonif** [comment]
It was a dependencies problem for me, after upgrading to angular 5.1.0. 
I deleted both node_modules folder and yarn.lock and magically the Issue disappared.
Don't  know why I did not have the problem with express...
Sorry for that, I miss a bit of experience.

**Comment by exequiel09** [comment]
I'll close it for now.
